const resList = [
  {
    id: "1",
    name: "Tasty Chile",
    cloudinaryImageId: "b5303a94c367062c158ce278bf6307a3",
    locality: "Mavoor Road",
    areaName: "Kuttichira",
    costForTwo: "₹400 for two",
    cuisines: [
      "South Indian",
      "Kerala",
      "Biryani",
      "Chinese",
      "Salads",
      "Seafood",
      "North Indian",
    ],
    avgRating: 4.3,
    timeTaken: "45 min",
  },
  {
    id: "2",
    name: "Hotel Sagar (Old Sagar)",
    cloudinaryImageId: "rapy3ovwlb9rp5udsvcr",
    locality: "Mavoor Road",
    areaName: "Kuttichira",
    costForTwo: "₹400 for two",
    cuisines: [
      "Chinese",
      "North Indian",
      "South Indian",
      "Ice Cream",
      "Biryani",
    ],
    avgRating: 4.3,
    timeTaken: "55 min",
  },
  {
    id: "3",
    name: "Hotel Sarovar",
    cloudinaryImageId: "ff12prdz1rmyzmxx3z3y",
    locality: "GH Road",
    areaName: "Palayam",
    costForTwo: "₹200 for two",
    cuisines: [
      "Chinese",
      "North Indian",
      "South Indian",
      "Ice Cream",
      "Biryani",
    ],
    avgRating: 4.3,
    timeTaken: "15 min",
  },
  {
    id: "4",
    name: "Domino's Pizza",
    cloudinaryImageId: "po2uphlrcawsfglehobb",
    locality: "Green Nagar",
    areaName: "Karaparamba",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4.4,
    timeTaken: "20 min",
  },
  {
    id: "5",
    name: "Chicking",
    cloudinaryImageId: "86f52324ecee5fc94cbf63c4a568b672",
    locality: "Bypass Road",
    areaName: "Ummalathoor",
    costForTwo: "₹300 for two",
    cuisines: [
      "Snacks",
      "Grill",
      "Fast Food",
      "American",
      "Pizzas",
      "Mexican",
      "Beverages",
    ],
    avgRating: 3.7,
    timeTaken: "20 min",
  },
  {
    id: "6",
    name: "Top Form_Mavoor Road",
    cloudinaryImageId: "b5303a94c367062c158ce278bf6307a3",
    locality: "Mavoor Road",
    areaName: "Kuttichira",
    costForTwo: "₹400 for two",
    cuisines: [
      "South Indian",
      "Kerala",
      "Biryani",
      "Chinese",
      "Salads",
      "Seafood",
      "North Indian",
    ],
    avgRating: 4.3,
    timeTaken: "20 min",
  },
  {
    id: "7",
    name: "Cita Pani",
    cloudinaryImageId: "cyvlgeod0xflvebl9kat",
    locality: "Moonalungal",
    areaName: "Kuttichira",
    costForTwo: "₹200 for two",
    cuisines: ["Arabian", "Snacks", "Beverages"],
    avgRating: 3.2,
    timeTaken: "20 min",
  },
  {
    id: "8",
    name: "Hotel Sagar (Old Sagar)",
    cloudinaryImageId: "rapy3ovwlb9rp5udsvcr",
    locality: "Mavoor Road",
    areaName: "Kuttichira",
    costForTwo: "₹400 for two",
    cuisines: [
      "Chinese",
      "North Indian",
      "South Indian",
      "Ice Cream",
      "Biryani",
    ],
    avgRating: 4.3,
    timeTaken: "20 min",
  },
  {
    id: "9",
    name: "Dessert Storm India(JAFFAH RETAIL)",
    cloudinaryImageId: "kqahy3yfduzz30mgpq2p",
    locality: "Mavoor Road",
    areaName: "Palayam",
    costForTwo: "₹300 for two",
    cuisines: ["Desserts", "Fast Food", "Ice Cream Cakes", "Waffle", "Juices"],
    avgRating: 4.2,
    timeTaken: "20 min",
  },
  {
    id: "10",
    name: "Cafe Dicaprio",
    cloudinaryImageId: "pu9who2f6x2wzad15uui",
    locality: "PT Usha Road",
    areaName: "Vellayil",
    costForTwo: "₹250 for two",
    cuisines: ["Pastas", "Chinese", "Burgers", "Ice Cream", "Pizzas"],
    avgRating: 3.5,
    timeTaken: "20 min",
  },
  {
    id: "11",
    name: "Bucket Bites",
    cloudinaryImageId: "ogbutaqxnn8kxyl47hum",
    locality: "Beach Road",
    areaName: "Vellayil",
    costForTwo: "₹250 for two",
    cuisines: [
      "Cafe",
      "Fast Food",
      "Snacks",
      "Arabian",
      "North Indian",
      "Tandoor",
      "Burgers",
    ],
    avgRating: 3.6,
    timeTaken: "22 min",
  },
  {
    id: "12",
    name: "Doner Club",
    cloudinaryImageId: "ryvtmvfbnw7kxcsao7t3",
    locality: "Indira Gandhi Road",
    areaName: "Palayam",
    costForTwo: "₹300 for two",
    cuisines: ["Arabian", "Kebabs", "Burgers", "Juices"],
    avgRating: 3.8,
    timeTaken: "20 min",
  },
];

export default resList;
